services:
  - type: web
    name: super-app-backend
    env: node
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false

  - type: web
    name: super-app-frontend
    env: static
    region: frankfurt
    plan: free
    buildCommand: flutter pub get && flutter build web --release --no-wasm-dry-run
    staticPublishPath: build/web
